[project]
name = 'stacks-circle-usdce-bridge'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[contracts.circle-usdce-token]
path = 'contracts/circle-usdce-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.token-traits]
path = 'contracts/traits/token-traits.clar'
clarity_version = 2
epoch = 2.4

[[project.requirements]]
contract_id = "SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-tokens-v1"

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
