
[project]
name = 'stacks-circle-usdce-bridge'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = "SP2J933XB2CP2JQ1A4FGN8JA968BBG3NK3EKZ7Q9F.hk-tokens-v1"

[contracts.token-traits]
path = 'contracts/traits/token-traits.clar'
clarity_version = 2
epoch = 2.4

[contracts.circle-usdc-token]
path = 'contracts/circle-usdc-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.usdc-test-extension]
path = 'contracts/tests/usdc-test-extension.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
